-- SELECT TOP 1 CAST (ROUND( 
--     ABS((SELECT TOP 1 LAT_N FROM STATION ORDER BY LAT_N ASC) - (SELECT TOP 1 LAT_N FROM STATION ORDER BY LAT_N DESC))
--     +
--     ABS((SELECT TOP 1 LONG_W  FROM STATION ORDER BY LONG_W  ASC) - (SELECT TOP 1 LONG_W  FROM STATION ORDER BY LONG_W DESC))
-- , 4) AS DECIMAL(18, 4))
-- FROM STATION;

SELECT TOP 1 CAST (ROUND(    
    ABS( MIN(LAT_N) - MAX(LAT_N) )
    +
    ABS( MIN(LONG_W ) - MAX(LONG_W ) )
, 4) AS DECIMAL(18, 4))
FROM STATION;
